- name: add python ppa
  action: apt_repository repo='ppa:fkrull/deadsnakes' update_cache=yes

- name: install python3.3
  action: apt pkg=${item} state=latest
  with_items: ${python_pkgs}

- name: install python3.3 ezsetup
  action: shell curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python3.3

- name: install python3.3 pip
  action: shell curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python3.3