- name: install supervisord
  action: pip name=supervisor
  
- name: install supervisord init control
  action: template src=../templates/init.supervisord.conf dest=/etc/init.d/supervisord
  
- name: configure supervisord init control
  action: shell sudo chmod +x /etc/init.d/supervisord && sudo update-rc.d supervisord defaults && sudo /etc/init.d/supervisord start
  
- name: make curb supervisor log dir
  action: file dest=/var/log/curb state=directory

- name: create config dir
  action: file dest=/etc/supervisord.d state=directory

- name: install supervisord config
  action: template src=../templates/supervisord.conf dest=/etc/supervisord.conf
  notify:
    - restart supervisord
