- name: install packages
  apt: pkg="{{ item }}" update_cache=yes
  with_items: basic_pkgs

- name: update ntp config
  copy: src=../files/ntp.conf dest=/etc/ntp.conf
  notify:
    - sync ntp
    - restart ntpd

- name: create var db directory
  file: dest=/var/db state=directory

- name: create groups
  group: name="{{ item }}" state=present
  with_items: groupz

- name: create users
  user: name="{{ item.user }}" groups="{{ item.groups }}" password="{{ item.pass }}"
  with_items: users

- name: create admin user ssh dir
  file: dest="/home/{{ item.user }}/.ssh" state=directory owner="{{ item.user }}"
  with_items: users

- name: add admin user pubkey
  template: src="../templates/{{ item.user }}/authorized_keys" dest="/home/{{ item.user }}/.ssh" owner="{{ item.user }}"
  with_items: users

- name: update sshd configuration
  template: src=../templates/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart sshd

- include: zsh.yml