- name: zprezto copy script
  copy: src=../files/zprezto_copy.sh dest="/home/{{ item.user }}/.zpcopy.sh" mode=0755 owner="{{ item.user }}"
  with_items: users

- name: remove old zprez
  shell: rm -rf /home/"{{ item.user }}"/.zpr*
  with_items: users

- name: install zprezto
  shell: executable=/usr/bin/zsh git clone --recursive https://github.com/sorin-ionescu/prezto.git "/home/{{ item.user }}/.zprezto"
  with_items: users
  notify:
    - copy zprezto
    - zsh default
    - zsh config